"""Municipal booking portals we can link to, from ``app/data/portals.json``.

Generated by ``python -m scripts.build_portal_catalog`` from the country-wide
portal survey (``scripts/sniff_portals.py``). One entry per municipality or
Kreis whose own website links to an appointment system.

These are **not** scanned. Either no adapter exists for the vendor, or the
instance has not been verified, so every entry carries ``scan_enabled=False``
and provider ``portal``. What they give the user is the thing that was missing:
type a postcode, get the authority that is actually responsible, and tap
through to its official booking page instead of searching for it.

The file is data rather than a Python module because there are thousands of
rows; a generated module that size is unreadable in review and slow to import.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from app.models.enums import AuthorityType, Provider

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "portals.json"


@lru_cache(maxsize=1)
def load_portals(path: Path = DATA_PATH) -> list[dict]:
    """Catalogue entries for every surveyed booking portal."""
    try:
        with path.open(encoding="utf-8") as handle:
            payload = json.load(handle)
    except FileNotFoundError:
        return []

    entries = []
    for row in payload["portals"]:
        entries.append(
            {
                "provider": Provider.PORTAL,
                "external_id": row["external_id"],
                "base_url": row["base_url"],
                "name": row["name"],
                "authority_type": AuthorityType(row["authority_type"]),
                "city": row["city"],
                "state": row["state"],
                "postal_code": row.get("postal_code"),
                "municipality_ags": row["ags"],
                "booking_url": row["booking_url"],
                "active": True,
                "scan_enabled": False,
                "scan_blocked_reason": row["scan_blocked_reason"],
                "provider_meta": {"vendor": row["vendor"], "source": "sniff_portals"},
            }
        )
    return entries


PORTAL_OFFICES: list[dict] = load_portals()
