"""TEVIS instances whose robots.txt permits polling, from ``app/data/tevis_offices.json``.

Generated by ``python -m scripts.build_tevis_catalog`` from the output of
``scripts/discover_tevis.py``. Each entry is one mandant on a TEVIS instance —
one bookable office — belonging either to a city or to a Kreis, whose
instance is filed on its seat municipality.

Street and postcode beyond the municipality's own are absent: a TEVIS landing
page names its offices but does not give their addresses. The app searches by
place and name in the meantime.

``scan_enabled`` is the robots.txt verdict for the instance's calendar path
(``/suggest``). ``verified`` records whether *this* instance has been read by
hand — false for all but a handful, even though the adapter itself has been
verified against a ten-instance sample covering all three deployment shapes
(own install, vendor-hosted, shared data centre). Nine of the ten answered
with real appointments; the tenth is a mandant configured to ask for personal
data before showing any, which the adapter refuses rather than fills in.

The deployment gate is still ``SCANNER_PROVIDERS``: enabling `tevis` means
polling public authorities, which is a decision for whoever runs the service.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

from app.models.enums import AuthorityType, Provider

DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "tevis_offices.json"

TEVIS_UNVERIFIED_NOTE = "Adapter gegen TEVIS verifiziert; diese Instanz nicht einzeln geprüft"


@lru_cache(maxsize=1)
def load_tevis_offices(path: Path = DATA_PATH) -> list[dict]:
    try:
        with path.open(encoding="utf-8") as handle:
            payload = json.load(handle)
    except FileNotFoundError:
        return []

    entries = []
    for row in payload["offices"]:
        entries.append(
            {
                "provider": Provider.TEVIS,
                "external_id": row["external_id"],
                "base_url": row["base_url"],
                "name": row["name"],
                "authority_type": AuthorityType(row["authority_type"]),
                "city": row["city"],
                "state": row["state"],
                "postal_code": row.get("postal_code"),
                "municipality_ags": row.get("ags"),
                "booking_url": row["booking_url"],
                "active": True,
                "scan_enabled": row["scan_enabled"],
                "scan_blocked_reason": row["scan_blocked_reason"],
                "provider_meta": {
                    "mandant": row["mandant"],
                    "verified": False,
                    "note": TEVIS_UNVERIFIED_NOTE,
                },
            }
        )
    return entries


TEVIS_CITY_OFFICES: list[dict] = load_tevis_offices()
