"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-18 19:14:16.389456

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db_types


revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', app.db_types.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('authority_type', sa.String(length=32), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('booking_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('cooldown_until', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('provider_meta', app.db_types.JSONType(), nullable=True),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_offices_provider_external_id')
    )
    op.create_index(op.f('ix_offices_active'), 'offices', ['active'], unique=False)
    op.create_index(op.f('ix_offices_authority_type'), 'offices', ['authority_type'], unique=False)
    op.create_index(op.f('ix_offices_city'), 'offices', ['city'], unique=False)
    op.create_index(op.f('ix_offices_postal_code'), 'offices', ['postal_code'], unique=False)
    op.create_index(op.f('ix_offices_provider'), 'offices', ['provider'], unique=False)
    op.create_table('users',
    sa.Column('id', app.db_types.GUID(), nullable=False),
    sa.Column('install_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_install_id'), 'users', ['install_id'], unique=True)
    op.create_table('devices',
    sa.Column('id', app.db_types.GUID(), nullable=False),
    sa.Column('user_id', app.db_types.GUID(), nullable=False),
    sa.Column('push_token', sa.String(length=256), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('invalidated_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('push_token', name='uq_devices_push_token')
    )
    op.create_index(op.f('ix_devices_active'), 'devices', ['active'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('services',
    sa.Column('id', app.db_types.GUID(), nullable=False),
    sa.Column('office_id', app.db_types.GUID(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('next_scan_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_id', 'external_id', name='uq_services_office_external_id')
    )
    op.create_index(op.f('ix_services_active'), 'services', ['active'], unique=False)
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_next_scan_at'), 'services', ['next_scan_at'], unique=False)
    op.create_index(op.f('ix_services_office_id'), 'services', ['office_id'], unique=False)
    op.create_table('watches',
    sa.Column('id', app.db_types.GUID(), nullable=False),
    sa.Column('user_id', app.db_types.GUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('earliest_date', sa.Date(), nullable=True),
    sa.Column('latest_date', sa.Date(), nullable=True),
    sa.Column('weekday_mask', sa.Integer(), nullable=False),
    sa.Column('earliest_time', sa.Time(), nullable=True),
    sa.Column('latest_time', sa.Time(), nullable=True),
    sa.Column('min_lead_hours', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('paused_until', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('expires_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('last_notified_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('notification_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watches_active'), 'watches', ['active'], unique=False)
    op.create_index(op.f('ix_watches_category'), 'watches', ['category'], unique=False)
    op.create_index(op.f('ix_watches_user_id'), 'watches', ['user_id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', app.db_types.GUID(), nullable=False),
    sa.Column('office_id', app.db_types.GUID(), nullable=False),
    sa.Column('service_id', app.db_types.GUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('started_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('finished_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('slots_seen', sa.Integer(), nullable=False),
    sa.Column('slots_new', sa.Integer(), nullable=False),
    sa.Column('slots_gone', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_runs_office_started', 'scan_runs', ['office_id', 'started_at'], unique=False)
    op.create_table('slots',
    sa.Column('id', app.db_types.GUID(), nullable=False),
    sa.Column('office_id', app.db_types.GUID(), nullable=False),
    sa.Column('service_id', app.db_types.GUID(), nullable=False),
    sa.Column('starts_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('ends_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('last_seen_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('gone_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('provider_ref', sa.String(length=512), nullable=True),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('office_id', 'service_id', 'starts_at', name='uq_slots_office_service_start')
    )
    op.create_index('ix_slots_first_seen_at', 'slots', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_slots_office_id'), 'slots', ['office_id'], unique=False)
    op.create_index(op.f('ix_slots_service_id'), 'slots', ['service_id'], unique=False)
    op.create_index(op.f('ix_slots_starts_at'), 'slots', ['starts_at'], unique=False)
    op.create_index(op.f('ix_slots_status'), 'slots', ['status'], unique=False)
    op.create_index('ix_slots_status_starts_at', 'slots', ['status', 'starts_at'], unique=False)
    op.create_table('watch_offices',
    sa.Column('watch_id', app.db_types.GUID(), nullable=False),
    sa.Column('office_id', app.db_types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watch_id', 'office_id')
    )
    op.create_table('booking_intents',
    sa.Column('id', app.db_types.GUID(), nullable=False),
    sa.Column('user_id', app.db_types.GUID(), nullable=False),
    sa.Column('slot_id', app.db_types.GUID(), nullable=False),
    sa.Column('watch_id', app.db_types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('handoff_url', sa.String(length=1024), nullable=False),
    sa.Column('resolved_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_intents_slot_id'), 'booking_intents', ['slot_id'], unique=False)
    op.create_index(op.f('ix_booking_intents_status'), 'booking_intents', ['status'], unique=False)
    op.create_index(op.f('ix_booking_intents_user_id'), 'booking_intents', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', app.db_types.GUID(), nullable=False),
    sa.Column('watch_id', app.db_types.GUID(), nullable=False),
    sa.Column('slot_id', app.db_types.GUID(), nullable=False),
    sa.Column('user_id', app.db_types.GUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('sent_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('read_at', app.db_types.UTCDateTime(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.db_types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db_types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watch_id', 'slot_id', name='uq_notifications_watch_slot')
    )
    op.create_index(op.f('ix_notifications_slot_id'), 'notifications', ['slot_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_watch_id'), 'notifications', ['watch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_watch_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_slot_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_booking_intents_user_id'), table_name='booking_intents')
    op.drop_index(op.f('ix_booking_intents_status'), table_name='booking_intents')
    op.drop_index(op.f('ix_booking_intents_slot_id'), table_name='booking_intents')
    op.drop_table('booking_intents')
    op.drop_table('watch_offices')
    op.drop_index('ix_slots_status_starts_at', table_name='slots')
    op.drop_index(op.f('ix_slots_status'), table_name='slots')
    op.drop_index(op.f('ix_slots_starts_at'), table_name='slots')
    op.drop_index(op.f('ix_slots_service_id'), table_name='slots')
    op.drop_index(op.f('ix_slots_office_id'), table_name='slots')
    op.drop_index('ix_slots_first_seen_at', table_name='slots')
    op.drop_table('slots')
    op.drop_index('ix_scan_runs_office_started', table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_watches_user_id'), table_name='watches')
    op.drop_index(op.f('ix_watches_category'), table_name='watches')
    op.drop_index(op.f('ix_watches_active'), table_name='watches')
    op.drop_table('watches')
    op.drop_index(op.f('ix_services_office_id'), table_name='services')
    op.drop_index(op.f('ix_services_next_scan_at'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_index(op.f('ix_services_active'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_active'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_install_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_offices_provider'), table_name='offices')
    op.drop_index(op.f('ix_offices_postal_code'), table_name='offices')
    op.drop_index(op.f('ix_offices_city'), table_name='offices')
    op.drop_index(op.f('ix_offices_authority_type'), table_name='offices')
    op.drop_index(op.f('ix_offices_active'), table_name='offices')
    op.drop_table('offices')
    # ### end Alembic commands ###
