"""watch alert limits

Revision ID: 0002_watch_alert_limits
Revises: 0001_initial
Create Date: 2026-08-22 08:40:15.361298

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0002_watch_alert_limits"
down_revision: str | Sequence[str] | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watches', sa.Column('daily_alert_limit', sa.Integer(), nullable=True))
    op.add_column('watches', sa.Column('auto_stop_after', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watches', 'auto_stop_after')
    op.drop_column('watches', 'daily_alert_limit')
    # ### end Alembic commands ###
