"""office scan flag

Revision ID: 0003_office_scan_flag
Revises: 0002_watch_alert_limits
Create Date: 2026-08-22 09:09:49.785482

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0003_office_scan_flag"
down_revision: str | Sequence[str] | None = '0002_watch_alert_limits'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('scan_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('offices', sa.Column('scan_blocked_reason', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_offices_scan_enabled'), 'offices', ['scan_enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offices_scan_enabled'), table_name='offices')
    op.drop_column('offices', 'scan_blocked_reason')
    op.drop_column('offices', 'scan_enabled')
    # ### end Alembic commands ###
