"""Turn the TEVIS discovery output into a catalogue module.

    python -m scripts.build_tevis_catalog --offices tevis_offices.json

Reads what `scripts/discover_tevis.py` found and writes
`app/catalog/tevis_cities.py`. Before an office is marked scannable, the
production robots matcher is asked about ``<base>/suggest`` — the calendar
path the adapter actually polls. The city survey only checked ``/select2``,
and a host is free to allow the landing page while forbidding the calendar.

Every entry carries ``provider_meta.verified = False``: the adapter has not
yet been run live against any of these instances. ``scan_enabled`` records
the *permission* (robots allows it); whether the deployment *does* poll is a
separate switch, ``SCANNER_PROVIDERS``, which stays closed until one instance
has been verified by hand. See docs/providers.md.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
from pathlib import Path

from app.providers.base import build_client
from app.providers.robots import robots
from app.providers.taxonomy import classify_authority

TARGET = Path(__file__).resolve().parent.parent / "app" / "catalog" / "tevis_cities.py"

HEADER = '''from __future__ import annotations

from app.models.enums import AuthorityType, Provider

#: TEVIS instances of large cities whose robots.txt permits polling.
#:
#: Generated by ``python -m scripts.build_tevis_catalog`` from the output of
#: ``scripts/discover_tevis.py``; do not hand-edit. Each entry is one mandant
#: on a city's TEVIS instance — one bookable office.
#:
#: Street and postcode are absent: a TEVIS landing page names its offices but
#: does not give their addresses. They can be filled in from the cities' own
#: portals later; the app searches by city and name in the meantime.
#:
#: ``scan_enabled`` is the robots.txt verdict for the instance's calendar path
#: (``/suggest``). ``verified`` is False throughout: no adapter has been run
#: live against these instances yet. The deployment gate is
#: ``SCANNER_PROVIDERS``, which stays closed until that has happened.
TEVIS_UNVERIFIED_NOTE = "Adapter noch nicht live gegen diese Instanz verifiziert"

TEVIS_CITY_OFFICES: list[dict] = [
'''

FOOTER = "]\n"


def slug(text: str) -> str:
    text = text.lower()
    for src, dst in (("ä", "ae"), ("ö", "oe"), ("ü", "ue"), ("ß", "ss")):
        text = text.replace(src, dst)
    return re.sub(r"[^a-z0-9]+", "-", text).strip("-")


def q(value: str | None) -> str:
    return "None" if value is None else json.dumps(value, ensure_ascii=False)


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--offices", required=True, help="discover_tevis.py JSON output")
    args = parser.parse_args()

    with open(args.offices, encoding="utf-8") as handle:
        outcomes = json.load(handle)

    offices = [o for outcome in outcomes for o in outcome["offices"]]
    offices.sort(key=lambda o: (o["city"], o["name"]))

    # One robots decision per instance, on the path that matters.
    verdicts: dict[str, tuple[bool, str]] = {}
    async with build_client() as client:
        for base_url in sorted({o["base_url"] for o in offices}):
            verdict = await robots.allowed(client, f"{base_url}/suggest")
            verdicts[base_url] = (verdict.allowed, verdict.reason)

    lines = [HEADER]
    for o in offices:
        allowed, reason = verdicts[o["base_url"]]
        authority = classify_authority(o["name"])
        external_id = f"tevis-{slug(o['city'])}-md{o['mandant']}"
        lines.append("    {\n")
        lines.append("        \"provider\": Provider.TEVIS,\n")
        lines.append(f"        \"external_id\": {q(external_id)},\n")
        lines.append(f"        \"base_url\": {q(o['base_url'])},\n")
        lines.append(f"        \"name\": {q(o['name'])},\n")
        lines.append(f"        \"authority_type\": AuthorityType.{authority.name},\n")
        lines.append(f"        \"city\": {q(o['city'])},\n")
        lines.append(f"        \"state\": {q(o['state'])},\n")
        lines.append(f"        \"booking_url\": {q(o['booking_url'])},\n")
        lines.append("        \"active\": True,\n")
        lines.append(f"        \"scan_enabled\": {allowed},\n")
        blocked = None if allowed else f"robots.txt: {o['base_url']}/suggest {reason}"
        lines.append(f"        \"scan_blocked_reason\": {q(blocked)},\n")
        lines.append(
            f"        \"provider_meta\": {{\"mandant\": {q(o['mandant'])}, \"verified\": False, "
            f"\"note\": TEVIS_UNVERIFIED_NOTE}},\n"
        )
        lines.append("    },\n")
    lines.append(FOOTER)

    TARGET.write_text("".join(lines), encoding="utf-8")

    by_city: dict[str, int] = {}
    for o in offices:
        by_city[o["city"]] = by_city.get(o["city"], 0) + 1
    print(f"wrote {TARGET} — {len(offices)} Ämter")
    for city, count in sorted(by_city.items()):
        base = next(o["base_url"] for o in offices if o["city"] == city)
        allowed, _ = verdicts[base]
        print(f"  {city:18} {count:3}  scan_enabled={allowed}")


if __name__ == "__main__":
    asyncio.run(main())
